# Generated by Django 3.2.16 on 2025-10-16 11:33

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_image_path, verbose_name='Изображение'),
        ),
    ]
