# Generated by Django 3.2.16 on 2025-10-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['-created_at', '-pk'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
